// 英文默认规则库。每条带 lang:'en'，detector 对 regex 自动用 'gi' flag（ASR 无大写可靠）。
// 来源：社区 AI-slop 抱怨调研（Reddit r/ChatGPT、HN、GPTZero/Originality.ai 博客、El País 学术用词研究）。
// 设计要点：
//   - 正则不强依赖标点（英文字幕多为 ASR 转写，常无句末标点）
//   - 用 \b 词边界防止子串误匹配（如 unlike 误命中 like）
//   - 陷阱词（actually/basically/just/really/literally/honestly 等）两边都不收录：
//     真人高频，口语化 AI 文案也高频，作正/负信号都会误伤
//   - 反向 human 类用负权重，只收「真人口语独有」的失语/缩略特征（uh/um/gonna/yeah 等）

export const EN_RULES = [
  // ── A 成对句式（证据最强）──────────────────────────────
  { id: "en_not_only_but", name: "not only…but…", category: "pair", kind: "regex", lang: "en",
    pattern: "not only\\b[^.!?;]{0,80}?\\bbut\\b", weight: 10, cap: 4, enabled: true },
  { id: "en_not_but_rather", name: "not…but rather", category: "pair", kind: "regex", lang: "en",
    pattern: "not\\s+\\w+\\s+but\\s+rather", weight: 10, cap: 3, enabled: true },
  { id: "en_is_not_x_but", name: "is not just/merely…but", category: "pair", kind: "regex", lang: "en",
    pattern: "is not (?:just|merely|simply)\\b[^.!?;]{0,40}?\\bbut\\b", weight: 9, cap: 3, enabled: true },
  { id: "en_not_only_that", name: "not only that", category: "pair", kind: "regex", lang: "en",
    pattern: "not only that\\b", weight: 7, cap: 2, enabled: true },
  { id: "en_whether_or", name: "whether…or", category: "pair", kind: "regex", lang: "en",
    pattern: "whether\\b[^.!?;]{0,60}?\\bor\\b", weight: 8, cap: 3, enabled: true },
  { id: "en_both_and", name: "both…and", category: "pair", kind: "regex", lang: "en",
    pattern: "both\\b[^.!?;]{0,40}?\\band\\b", weight: 6, cap: 3, enabled: true },
  { id: "en_either_or", name: "either…or", category: "pair", kind: "regex", lang: "en",
    pattern: "either\\b[^.!?;]{0,60}?\\bor\\b", weight: 5, cap: 3, enabled: true },
  { id: "en_neither_nor", name: "neither…nor", category: "pair", kind: "regex", lang: "en",
    pattern: "neither\\b[^.!?;]{0,60}?\\bnor\\b", weight: 9, cap: 3, enabled: true },
  { id: "en_on_one_hand", name: "on the one hand…on the other", category: "pair", kind: "regex", lang: "en",
    pattern: "on the one hand[^.!?;]{0,80}?on the other hand", weight: 10, cap: 2, enabled: true },
  { id: "en_the_more", name: "the more…the more", category: "pair", kind: "regex", lang: "en",
    pattern: "the more[^.!?;]{0,40}?the more", weight: 7, cap: 2, enabled: true },
  { id: "en_no_matter", name: "no matter how/what/where", category: "pair", kind: "regex", lang: "en",
    pattern: "no matter (?:how|what|where|who|when)", weight: 5, cap: 3, enabled: true },
  { id: "en_whether_or_not", name: "whether or not", category: "pair", kind: "keyword", lang: "en",
    pattern: "whether or not", weight: 5, cap: 3, enabled: true },
  { id: "en_that_being_said", name: "that being said", category: "pair", kind: "keyword", lang: "en",
    pattern: "that being said", weight: 6, cap: 3, enabled: true },
  { id: "en_in_other_words", name: "in other words", category: "pair", kind: "keyword", lang: "en",
    pattern: "in other words", weight: 6, cap: 3, enabled: true },
  { id: "en_last_but_not_least", name: "last but not least", category: "pair", kind: "keyword", lang: "en",
    pattern: "last but not least", weight: 5, cap: 2, enabled: true },
  { id: "en_as_well_as", name: "as well as", category: "pair", kind: "keyword", lang: "en",
    pattern: "as well as", weight: 3, cap: 4, enabled: true },

  // ── B AI 高频连接/总结语（口语几乎不用）────────────────
  { id: "en_moreover", name: "moreover", category: "connect", kind: "keyword", lang: "en", pattern: "moreover", weight: 8, cap: 3, enabled: true },
  { id: "en_furthermore", name: "furthermore", category: "connect", kind: "keyword", lang: "en", pattern: "furthermore", weight: 9, cap: 3, enabled: true },
  { id: "en_additionally", name: "additionally", category: "connect", kind: "keyword", lang: "en", pattern: "additionally", weight: 8, cap: 3, enabled: true },
  { id: "en_in_conclusion", name: "in conclusion", category: "connect", kind: "keyword", lang: "en", pattern: "in conclusion", weight: 10, cap: 4, enabled: true },
  { id: "en_worth_noting", name: "it's worth noting", category: "connect", kind: "regex", lang: "en", pattern: "it(?:'s| is) worth noting", weight: 11, cap: 3, enabled: true },
  { id: "en_needless", name: "needless to say", category: "connect", kind: "keyword", lang: "en", pattern: "needless to say", weight: 8, cap: 2, enabled: true },
  { id: "en_goes_without", name: "it goes without saying", category: "connect", kind: "keyword", lang: "en", pattern: "it goes without saying", weight: 9, cap: 2, enabled: true },
  { id: "en_in_summary", name: "in summary", category: "connect", kind: "keyword", lang: "en", pattern: "in summary", weight: 7, cap: 3, enabled: true },
  { id: "en_when_it_comes", name: "when it comes to", category: "connect", kind: "keyword", lang: "en", pattern: "when it comes to", weight: 5, cap: 3, enabled: true },
  { id: "en_firstly_lastly", name: "firstly…lastly", category: "connect", kind: "all", lang: "en", pattern: ["firstly", "lastly"], weight: 7, cap: 2, enabled: true },
  { id: "en_ultimately", name: "ultimately", category: "connect", kind: "keyword", lang: "en", pattern: "ultimately", weight: 4, cap: 3, enabled: true },
  { id: "en_notably", name: "notably", category: "connect", kind: "keyword", lang: "en", pattern: "notably", weight: 5, cap: 3, enabled: true },
  { id: "en_more_importantly", name: "more importantly", category: "connect", kind: "keyword", lang: "en", pattern: "more importantly", weight: 7, cap: 3, enabled: true },
  { id: "en_importantly", name: "importantly", category: "connect", kind: "keyword", lang: "en", pattern: "importantly", weight: 4, cap: 3, enabled: true },
  { id: "en_as_mentioned", name: "as mentioned earlier", category: "connect", kind: "keyword", lang: "en", pattern: "as mentioned earlier", weight: 8, cap: 3, enabled: true },
  { id: "en_as_discussed", name: "as we discussed", category: "connect", kind: "keyword", lang: "en", pattern: "as we discussed", weight: 6, cap: 2, enabled: true },
  { id: "en_important_to_note", name: "it's important to note", category: "connect", kind: "regex", lang: "en",
    pattern: "it(?:'s| is|s) important to note", weight: 10, cap: 3, enabled: true },
  { id: "en_should_be_noted", name: "it should be noted", category: "connect", kind: "keyword", lang: "en",
    pattern: "it should be noted", weight: 9, cap: 2, enabled: true },
  { id: "en_no_surprise", name: "it's no surprise", category: "connect", kind: "regex", lang: "en",
    pattern: "it(?:'s| is|s) no surprise", weight: 6, cap: 3, enabled: true },
  { id: "en_thus", name: "thus", category: "connect", kind: "keyword", lang: "en", pattern: "thus", weight: 5, cap: 3, enabled: true },
  { id: "en_consequently", name: "consequently", category: "connect", kind: "keyword", lang: "en", pattern: "consequently", weight: 7, cap: 3, enabled: true },
  { id: "en_therefore", name: "therefore", category: "connect", kind: "keyword", lang: "en", pattern: "therefore", weight: 3, cap: 4, enabled: true },
  { id: "en_as_a_result", name: "as a result", category: "connect", kind: "keyword", lang: "en", pattern: "as a result", weight: 3, cap: 4, enabled: true },
  { id: "en_overall", name: "overall", category: "connect", kind: "keyword", lang: "en", pattern: "overall", weight: 3, cap: 3, enabled: true },
  { id: "en_in_essence", name: "in essence", category: "connect", kind: "keyword", lang: "en", pattern: "in essence", weight: 7, cap: 3, enabled: true },
  { id: "en_to_sum_up", name: "to sum up", category: "connect", kind: "keyword", lang: "en", pattern: "to sum up", weight: 7, cap: 2, enabled: true },
  { id: "en_to_some_extent", name: "to some extent", category: "connect", kind: "keyword", lang: "en", pattern: "to some extent", weight: 5, cap: 3, enabled: true },
  { id: "en_to_a_certain_extent", name: "to a certain extent", category: "connect", kind: "keyword", lang: "en", pattern: "to a certain extent", weight: 6, cap: 2, enabled: true },
  { id: "en_for_instance", name: "for instance", category: "connect", kind: "keyword", lang: "en", pattern: "for instance", weight: 4, cap: 3, enabled: true },
  { id: "en_first_and_foremost", name: "first and foremost", category: "connect", kind: "keyword", lang: "en", pattern: "first and foremost", weight: 7, cap: 2, enabled: true },
  { id: "en_picture_this", name: "picture this", category: "connect", kind: "keyword", lang: "en", pattern: "picture this", weight: 5, cap: 3, enabled: true },
  { id: "en_the_fact_that", name: "the fact that", category: "connect", kind: "keyword", lang: "en", pattern: "the fact that", weight: 3, cap: 5, enabled: true },
  { id: "en_not_just_about", name: "not just about", category: "connect", kind: "regex", lang: "en",
    pattern: "it(?:'s| is|s) not (?:just|only|simply) about", weight: 8, cap: 3, enabled: true },
  { id: "en_at_its_core", name: "at its core", category: "connect", kind: "keyword", lang: "en", pattern: "at its core", weight: 7, cap: 2, enabled: true },
  { id: "en_wide_range", name: "a wide range of", category: "connect", kind: "keyword", lang: "en", pattern: "a wide range of", weight: 6, cap: 3, enabled: true },
  { id: "en_the_importance", name: "the importance of", category: "connect", kind: "keyword", lang: "en", pattern: "the importance of", weight: 5, cap: 3, enabled: true },
  { id: "en_the_beauty", name: "the beauty of", category: "connect", kind: "keyword", lang: "en", pattern: "the beauty of", weight: 5, cap: 2, enabled: true },

  // ── B2 脚本式连读/陈词（口语化 AI 文案高频，真人偶尔）──────
  { id: "en_you_will_find", name: "you will find / you'll find", category: "connect", kind: "regex", lang: "en",
    pattern: "you(?:'ll| will) find", weight: 4, cap: 3, enabled: true },
  { id: "en_the_key", name: "the key (thing/point) is", category: "connect", kind: "regex", lang: "en",
    pattern: "the key (?:thing|point|takeaway)[^.!?;]{0,12}? is", weight: 5, cap: 3, enabled: true },
  { id: "en_comes_down_to", name: "it comes down to", category: "connect", kind: "keyword", lang: "en",
    pattern: "it comes down to", weight: 5, cap: 3, enabled: true },
  { id: "en_bottom_line", name: "the bottom line is", category: "connect", kind: "keyword", lang: "en",
    pattern: "the bottom line is", weight: 6, cap: 2, enabled: true },
  { id: "en_what_this_means", name: "what this/that means is", category: "connect", kind: "regex", lang: "en",
    pattern: "what (?:this|that) means is", weight: 6, cap: 3, enabled: true },
  { id: "en_important_because", name: "this is important because", category: "connect", kind: "keyword", lang: "en",
    pattern: "this is important because", weight: 5, cap: 2, enabled: true },
  { id: "en_keep_in_mind", name: "keep in mind that", category: "connect", kind: "keyword", lang: "en",
    pattern: "keep in mind", weight: 4, cap: 2, enabled: true },
  { id: "en_you_might_ask", name: "you might ask/wonder", category: "connect", kind: "regex", lang: "en",
    pattern: "you (?:might|may) (?:ask|wonder|be thinking)", weight: 6, cap: 3, enabled: true },
  { id: "en_put_simply", name: "simply put / put simply", category: "connect", kind: "regex", lang: "en",
    pattern: "(?:simply put|put simply)", weight: 6, cap: 2, enabled: true },
  { id: "en_in_the_long_run", name: "in the long run", category: "connect", kind: "keyword", lang: "en",
    pattern: "in the long run", weight: 4, cap: 2, enabled: true },
  { id: "en_by_and_large", name: "by and large", category: "connect", kind: "keyword", lang: "en",
    pattern: "by and large", weight: 5, cap: 2, enabled: true },
  { id: "en_for_the_most_part", name: "for the most part", category: "connect", kind: "keyword", lang: "en",
    pattern: "for the most part", weight: 4, cap: 2, enabled: true },
  { id: "en_safe_to_say", name: "it's safe to say", category: "connect", kind: "regex", lang: "en",
    pattern: "it(?:'s| is|s) safe to say", weight: 7, cap: 2, enabled: true },
  { id: "en_fair_to_say", name: "it's fair to say", category: "connect", kind: "regex", lang: "en",
    pattern: "it(?:'s| is|s) fair to say", weight: 6, cap: 2, enabled: true },
  { id: "en_truth_is", name: "the truth is", category: "connect", kind: "keyword", lang: "en",
    pattern: "the truth is", weight: 5, cap: 2, enabled: true },
  { id: "en_one_of_the_most", name: "one of the most", category: "connect", kind: "keyword", lang: "en",
    pattern: "one of the most", weight: 3, cap: 3, enabled: true },
  { id: "en_first_of_all", name: "first of all", category: "connect", kind: "keyword", lang: "en",
    pattern: "first of all", weight: 3, cap: 2, enabled: true },
  { id: "en_if_you_wondering", name: "if you're wondering", category: "connect", kind: "regex", lang: "en",
    pattern: "if you(?:'re| are) wondering", weight: 5, cap: 2, enabled: true },

  // ── C 翻译腔/学术腔（社区公认 AI spike 词）─────────────
  { id: "en_delve", name: "delve(incl. variants)", category: "academic", kind: "regex", lang: "en", pattern: "delve\\w*", weight: 12, cap: 5, enabled: true },
  { id: "en_meticulous", name: "meticulous(meticulously)", category: "academic", kind: "regex", lang: "en", pattern: "meticulous\\w*", weight: 11, cap: 4, enabled: true },
  { id: "en_intricate", name: "intricate", category: "academic", kind: "keyword", lang: "en", pattern: "intricate", weight: 10, cap: 4, enabled: true },
  { id: "en_testament", name: "a testament to", category: "academic", kind: "regex", lang: "en", pattern: "(?:a|an)? testament to", weight: 10, cap: 3, enabled: true },
  { id: "en_plays_role", name: "plays a (crucial) role", category: "academic", kind: "regex", lang: "en",
    pattern: "plays? (?:a|an|the) (?:crucial|vital|key|essential|important|pivotal|significant) role", weight: 7, cap: 3, enabled: true },
  { id: "en_navigate_complex", name: "navigate the complexities", category: "academic", kind: "regex", lang: "en", pattern: "navigate the complex", weight: 11, cap: 3, enabled: true },
  { id: "en_todays_world", name: "in today's world", category: "academic", kind: "regex", lang: "en", pattern: "in today('s|s)? world", weight: 9, cap: 4, enabled: true },
  { id: "en_serves_as", name: "serves as", category: "academic", kind: "keyword", lang: "en", pattern: "serves as", weight: 7, cap: 3, enabled: true },
  { id: "en_multifaceted", name: "multifaceted", category: "academic", kind: "keyword", lang: "en", pattern: "multifaceted", weight: 9, cap: 3, enabled: true },
  { id: "en_digital_age", name: "in the digital age", category: "academic", kind: "keyword", lang: "en", pattern: "in the digital age", weight: 9, cap: 3, enabled: true },
  { id: "en_tapestry", name: "tapestry", category: "academic", kind: "keyword", lang: "en", pattern: "tapestry", weight: 10, cap: 2, enabled: true },
  { id: "en_embark", name: "embark", category: "academic", kind: "regex", lang: "en", pattern: "embark\\w*", weight: 9, cap: 3, enabled: true },
  { id: "en_harness", name: "harness", category: "academic", kind: "regex", lang: "en", pattern: "harness\\w*", weight: 8, cap: 3, enabled: true },
  { id: "en_unleash", name: "unleash", category: "academic", kind: "regex", lang: "en", pattern: "unleash\\w*", weight: 7, cap: 3, enabled: true },
  { id: "en_elevate", name: "elevate", category: "academic", kind: "regex", lang: "en", pattern: "elevat\\w*", weight: 6, cap: 3, enabled: true },
  { id: "en_empower", name: "empower", category: "academic", kind: "regex", lang: "en", pattern: "empower\\w*", weight: 6, cap: 3, enabled: true },
  { id: "en_streamline", name: "streamline", category: "academic", kind: "regex", lang: "en", pattern: "streamlin\\w*", weight: 6, cap: 3, enabled: true },
  { id: "en_optimize", name: "optimize", category: "academic", kind: "regex", lang: "en", pattern: "optimiz\\w*", weight: 4, cap: 3, enabled: true },
  { id: "en_enhance", name: "enhance", category: "academic", kind: "regex", lang: "en", pattern: "enhanc\\w*", weight: 4, cap: 3, enabled: true },
  { id: "en_pivotal", name: "pivotal", category: "academic", kind: "keyword", lang: "en", pattern: "pivotal", weight: 8, cap: 3, enabled: true },
  { id: "en_crucial", name: "crucial", category: "academic", kind: "keyword", lang: "en", pattern: "crucial", weight: 4, cap: 3, enabled: true },
  { id: "en_vital", name: "vital", category: "academic", kind: "keyword", lang: "en", pattern: "vital", weight: 4, cap: 2, enabled: true },
  { id: "en_paramount", name: "paramount", category: "academic", kind: "keyword", lang: "en", pattern: "paramount", weight: 8, cap: 2, enabled: true },
  { id: "en_indispensable", name: "indispensable", category: "academic", kind: "keyword", lang: "en", pattern: "indispensable", weight: 8, cap: 2, enabled: true },
  { id: "en_landscape", name: "landscape", category: "academic", kind: "keyword", lang: "en", pattern: "landscape", weight: 6, cap: 3, enabled: true },
  { id: "en_realm", name: "realm", category: "academic", kind: "keyword", lang: "en", pattern: "realm", weight: 6, cap: 3, enabled: true },
  { id: "en_journey", name: "journey", category: "academic", kind: "keyword", lang: "en", pattern: "journey", weight: 5, cap: 3, enabled: true },
  { id: "en_comprehensive", name: "comprehensive", category: "academic", kind: "keyword", lang: "en", pattern: "comprehensive", weight: 6, cap: 3, enabled: true },
  { id: "en_in_depth", name: "in-depth", category: "academic", kind: "regex", lang: "en", pattern: "in[- ]depth", weight: 4, cap: 3, enabled: true },
  { id: "en_cutting_edge", name: "cutting-edge", category: "academic", kind: "regex", lang: "en", pattern: "cutting[- ]edge", weight: 6, cap: 2, enabled: true },
  { id: "en_state_of_the_art", name: "state-of-the-art", category: "academic", kind: "regex", lang: "en",
    pattern: "state[- ]of[- ]the[- ]art", weight: 7, cap: 2, enabled: true },
  { id: "en_groundbreaking", name: "groundbreaking", category: "academic", kind: "keyword", lang: "en", pattern: "groundbreaking", weight: 8, cap: 2, enabled: true },
  { id: "en_transformative", name: "transformative", category: "academic", kind: "keyword", lang: "en", pattern: "transformative", weight: 8, cap: 3, enabled: true },
  { id: "en_revolutionize", name: "revolutionize", category: "academic", kind: "regex", lang: "en", pattern: "revolutioniz\\w*", weight: 9, cap: 2, enabled: true },
  { id: "en_myriad", name: "myriad", category: "academic", kind: "keyword", lang: "en", pattern: "myriad", weight: 8, cap: 2, enabled: true },
  { id: "en_nuanced", name: "nuanced", category: "academic", kind: "keyword", lang: "en", pattern: "nuanced", weight: 7, cap: 2, enabled: true },
  { id: "en_profound", name: "profound", category: "academic", kind: "keyword", lang: "en", pattern: "profound", weight: 6, cap: 2, enabled: true },
  { id: "en_underscore", name: "underscore", category: "academic", kind: "regex", lang: "en", pattern: "underscor\\w*", weight: 7, cap: 2, enabled: true },
  { id: "en_unveil", name: "unveil", category: "academic", kind: "regex", lang: "en", pattern: "unveil\\w*", weight: 7, cap: 2, enabled: true },
  { id: "en_showcase", name: "showcase", category: "academic", kind: "regex", lang: "en", pattern: "showcas\\w*", weight: 4, cap: 3, enabled: true },
  { id: "en_unprecedented", name: "unprecedented", category: "academic", kind: "keyword", lang: "en", pattern: "unprecedented", weight: 8, cap: 2, enabled: true },
  { id: "en_essential_to", name: "it's essential to", category: "academic", kind: "regex", lang: "en",
    pattern: "it(?:'s| is|s) essential to", weight: 9, cap: 2, enabled: true },
  { id: "en_world_of", name: "the world of", category: "academic", kind: "keyword", lang: "en", pattern: "the world of", weight: 4, cap: 3, enabled: true },
  { id: "en_dive_into", name: "dive into", category: "academic", kind: "keyword", lang: "en", pattern: "dive into", weight: 4, cap: 3, enabled: true },

  // ── D 营销大词（误伤风险较高，权重适中）──────────────
  { id: "en_synergy", name: "synergy", category: "buzzword", kind: "keyword", lang: "en", pattern: "synergy", weight: 8, cap: 2, enabled: true },
  { id: "en_paradigm", name: "paradigm", category: "buzzword", kind: "keyword", lang: "en", pattern: "paradigm", weight: 7, cap: 3, enabled: true },
  { id: "en_holistic", name: "holistic", category: "buzzword", kind: "keyword", lang: "en", pattern: "holistic", weight: 6, cap: 2, enabled: true },
  { id: "en_leverage", name: "leverage", category: "buzzword", kind: "regex", lang: "en", pattern: "leverag\\w*", weight: 6, cap: 3, enabled: true },
  { id: "en_seamless", name: "seamless", category: "buzzword", kind: "regex", lang: "en", pattern: "seamless\\w*", weight: 6, cap: 3, enabled: true },
  { id: "en_unlock", name: "unlock", category: "buzzword", kind: "regex", lang: "en", pattern: "unlock\\w*", weight: 5, cap: 2, enabled: true },
  { id: "en_game_changer", name: "game-changer", category: "buzzword", kind: "regex", lang: "en", pattern: "game[-\\s]?changer", weight: 5, cap: 2, enabled: true },
  { id: "en_futuristic", name: "futuristic", category: "buzzword", kind: "keyword", lang: "en", pattern: "futuristic", weight: 5, cap: 2, enabled: true },
  { id: "en_innovative", name: "innovative", category: "buzzword", kind: "keyword", lang: "en", pattern: "innovative", weight: 3, cap: 3, enabled: true },

  // ── E YouTuber 套话（真人也高频，低权重）──────────────
  { id: "en_without_ado", name: "without further ado", category: "outro", kind: "keyword", lang: "en", pattern: "without further ado", weight: 4, cap: 2, enabled: true },
  { id: "en_lets_dive_in", name: "let's dive in", category: "outro", kind: "regex", lang: "en", pattern: "let(?:'s|s)? dive in", weight: 4, cap: 2, enabled: true },
  { id: "en_stick_around", name: "stick around", category: "outro", kind: "keyword", lang: "en", pattern: "stick around", weight: 3, cap: 2, enabled: true },
  { id: "en_smash_subscribe", name: "smash that subscribe", category: "outro", kind: "regex", lang: "en", pattern: "smash (?:that|the) (?:subscribe|like|bell)", weight: 2, cap: 2, enabled: true },
  { id: "en_break_down", name: "let's break it down", category: "outro", kind: "regex", lang: "en", pattern: "let(?:'s|s)? break (?:it|this) down", weight: 3, cap: 2, enabled: true },
  { id: "en_today_were", name: "today we're going to", category: "outro", kind: "regex", lang: "en",
    pattern: "today we(?:'re| are) going to (?:talk about|discuss|explore|look at|cover)", weight: 3, cap: 2, enabled: true },
  { id: "en_thanks_watching", name: "thanks for watching", category: "outro", kind: "keyword", lang: "en", pattern: "thanks for watching", weight: 1, cap: 1, enabled: true },
  { id: "en_before_we_begin", name: "before we begin", category: "outro", kind: "regex", lang: "en", pattern: "before we (?:begin|get started|dive in)", weight: 3, cap: 2, enabled: true },

  // ── F 结构统计（detector 按 lang=en 选 *_en 实现）─────
  { id: "en_struct_dash", name: "破折号密度偏高", category: "structure", kind: "structure", lang: "en", pattern: "dash_density", weight: 4, cap: 4, enabled: true },
  { id: "en_struct_parallel3", name: "三连排比偏多", category: "structure", kind: "structure", lang: "en", pattern: "parallel3", weight: 5, cap: 4, enabled: true },
  { id: "en_struct_uniform", name: "句长过于均匀", category: "structure", kind: "structure", lang: "en", pattern: "sentence_uniform", weight: 3, cap: 3, enabled: true },
  { id: "en_struct_but", name: "however/nevertheless 转折偏多", category: "structure", kind: "structure", lang: "en", pattern: "but_transition", weight: 6, cap: 4, enabled: true },
  { id: "en_struct_written", name: "书面文本风格（大写+句读）", category: "structure", kind: "structure", lang: "en", pattern: "written_style", weight: 2, cap: 3, enabled: true },
  { id: "en_struct_semicolon", name: "分号密度", category: "structure", kind: "structure", lang: "en", pattern: "semicolon", weight: 4, cap: 3, enabled: true },
  { id: "en_struct_paren", name: "括号密度", category: "structure", kind: "structure", lang: "en", pattern: "paren", weight: 3, cap: 3, enabled: true },

  // ── G 反向规则·人类口语（负权重）─────────────────────
  { id: "en_human_uh", name: "uh（口语填充）", category: "human", kind: "regex", lang: "en", pattern: "\\buh\\b", weight: -4, cap: 2, enabled: true },
  { id: "en_human_um", name: "um（口语填充）", category: "human", kind: "regex", lang: "en", pattern: "\\bum\\b", weight: -4, cap: 2, enabled: true },
  { id: "en_human_you_know", name: "you know", category: "human", kind: "keyword", lang: "en", pattern: "you know", weight: -3, cap: 3, enabled: true },
  { id: "en_human_i_mean", name: "I mean", category: "human", kind: "keyword", lang: "en", pattern: "i mean", weight: -3, cap: 3, enabled: true },
  { id: "en_human_i_guess", name: "I guess", category: "human", kind: "keyword", lang: "en", pattern: "i guess", weight: -3, cap: 2, enabled: true },
  { id: "en_human_kind_of", name: "kind of / sort of", category: "human", kind: "regex", lang: "en", pattern: "(?:kind|sort) of", weight: -3, cap: 3, enabled: true },
  { id: "en_human_i_dunno", name: "I dunno / I don't know", category: "human", kind: "regex", lang: "en", pattern: "i (?:dunno|don'?t know)", weight: -4, cap: 3, enabled: true },
  { id: "en_human_so_yeah", name: "so yeah", category: "human", kind: "keyword", lang: "en", pattern: "so yeah", weight: -4, cap: 2, enabled: true },
  { id: "en_human_gonna", name: "gonna / wanna / gotta", category: "human", kind: "regex", lang: "en", pattern: "\\b(?:gonna|wanna|gotta)\\b", weight: -5, cap: 4, enabled: true },
  { id: "en_human_kinda", name: "kinda / sorta", category: "human", kind: "regex", lang: "en", pattern: "\\b(?:kinda|sorta)\\b", weight: -4, cap: 3, enabled: true },
  { id: "en_human_colloquial", name: "ain't / dunno / cuz / y'all", category: "human", kind: "regex", lang: "en", pattern: "\\b(?:ain'?t|dunno|cuz|coz|y'all|yall)\\b", weight: -5, cap: 4, enabled: true },
  { id: "en_human_yeah", name: "yeah / yep / nah / nope", category: "human", kind: "regex", lang: "en", pattern: "\\b(?:yeah|yep|nah|nope)\\b", weight: -2, cap: 4, enabled: true },
  { id: "en_human_okay", name: "okay / ok / alright / oh / hey", category: "human", kind: "regex", lang: "en", pattern: "\\b(?:okay|ok|alright|oh|hey)\\b", weight: -1, cap: 5, enabled: true },
  { id: "en_human_filler", name: "well / like / hmm / haha", category: "human", kind: "regex", lang: "en", pattern: "\\b(?:well|like|hmm|haha)\\b", weight: -1, cap: 6, enabled: true }
];